version: 0.0
os: linux
files:
  - source: /target/hello-world-1.0.0.jar
    destination: /home/ubuntu/application
hooks:
  Install:
    - location: scripts/start.sh
      timeout: 300
      runas: root
#  AfterInstall:
#    - location: scripts/change_permissions.sh
#      timeout: 300
#      runas: root
#  ApplicationStart:
#    - location: scripts/start_server.sh
#    - location: scripts/create_test_db.sh
#      timeout: 300
#      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server.sh
#      timeout: 300
#      runas: root
